# Generated by Django 5.1.5 on 2025-03-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=50)),
                ('stransmission', models.CharField(choices=[('Manual', 'Manual'), ('Auto', 'Auto')], max_length=50)),
                ('cname', models.CharField(max_length=100)),
                ('mileage', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('luggage', models.IntegerField()),
            ],
        ),
    ]
