# Generated by Django 5.1.5 on 2025-03-05 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ABS',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='Airbag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='Bluetooth',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='Camera',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='Car_Kit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='Child_Seat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='Climate_control',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='Cruise_Control',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='Music',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='Parking_Sensor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='Seat_Belt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='air',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='gps',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='lessor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='sfuel',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('CNG', 'CNG')], max_length=50),
        ),
    ]
