# Generated by Django 5.1.5 on 2025-03-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_car_abs_car_airbag_car_bluetooth_car_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cimage',
            field=models.ImageField(default='user.png', upload_to=''),
        ),
    ]
