# Generated by Django 5.1.5 on 2025-03-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_car_cimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ABS',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='Airbag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='Bluetooth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='Camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='Car_Kit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='Child_Seat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='Climate_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='Cruise_Control',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='Music',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='Parking_Sensor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='Seat_Belt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='air',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='gps',
            field=models.BooleanField(default=False),
        ),
    ]
