# Generated by Django 5.1.5 on 2025-03-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_car_abs_alter_car_airbag_alter_car_bluetooth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='hprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='mprice',
            field=models.IntegerField(default=0),
        ),
    ]
