# Generated by Django 5.1.5 on 2025-03-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reject_status',
            field=models.BooleanField(default=False),
        ),
    ]
